"use client";

import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useVariablesScope } from "@/features/workflows/workflow-properties/variables-scope";
import {
  friendlyTypeLabel,
  shortenTypeName,
} from "@/features/workflows/workflow-properties/type-display";
import { useStorageDrivers, useVariableTypes } from "@/lib/api/elsa";
import type {
  StorageDriverDescriptor,
  VariableDefinition,
  VariableTypeDescriptor,
} from "@/lib/api/types";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Called with the created variable so callers can auto-select it. */
  onCreated?: (variable: VariableDefinition) => void;
  /** Optional initial name (e.g., from an autogenerated suggestion). */
  initialName?: string;
};

/**
 * Shared dialog for creating a workflow variable. Mirrors the Blazor
 * `EditVariableDialog` field set: Name, Type (grouped by category),
 * Is Array, Default value, Storage driver. The new variable is pushed
 * straight onto the in-memory `definition.variables`; persistence happens
 * via the normal Save flow.
 */
export function CreateVariableDialog({ open, onOpenChange, onCreated, initialName }: Props) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        {open ? (
          <CreateForm
            onClose={() => onOpenChange(false)}
            onCreated={onCreated}
            initialName={initialName}
          />
        ) : null}
      </DialogContent>
    </Dialog>
  );
}

function CreateForm({
  onClose,
  onCreated,
  initialName,
}: {
  onClose: () => void;
  onCreated?: (variable: VariableDefinition) => void;
  initialName?: string;
}) {
  const scopeBundle = useVariablesScope();
  const existing = useMemo(() => scopeBundle?.variables ?? [], [scopeBundle?.variables]);

  const types = useVariableTypes();
  const drivers = useStorageDrivers();

  const defaultName = useMemo(() => {
    if (initialName) return initialName;
    let i = existing.length + 1;
    let candidate = `Variable${i}`;
    while (existing.some((v) => v.name === candidate)) {
      i += 1;
      candidate = `Variable${i}`;
    }
    return candidate;
  }, [existing, initialName]);

  const [name, setName] = useState(defaultName);
  const [typeName, setTypeName] = useState<string>("");
  const [isArray, setIsArray] = useState(false);
  const [value, setValue] = useState("");
  const [storage, setStorage] = useState<string>("");

  // Pick sensible defaults once their respective queries resolve.
  useEffect(() => {
    if (!types.data || types.data.length === 0 || typeName) return;
    const preferred = types.data.find((t) => t.typeName === "System.String");
    setTypeName(preferred?.typeName ?? types.data[0].typeName);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [types.data]);

  useEffect(() => {
    if (!drivers.data || drivers.data.length === 0 || storage) return;
    const preferred = drivers.data.find((d) => !d.deprecated) ?? drivers.data[0];
    setStorage(preferred.typeName);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drivers.data]);

  // Build the items list base-ui uses to render the trigger label correctly.
  const typeItems = useMemo(
    () =>
      (types.data ?? []).map((t) => ({
        label: friendlyTypeName(t),
        value: t.typeName,
      })),
    [types.data],
  );

  const groupedTypes = useMemo(() => {
    const buckets = new Map<string, VariableTypeDescriptor[]>();
    for (const t of types.data ?? []) {
      const key = t.category?.trim() || "Other";
      const list = buckets.get(key) ?? [];
      list.push(t);
      buckets.set(key, list);
    }
    return [...buckets.entries()].sort(([a], [b]) => a.localeCompare(b));
  }, [types.data]);

  const driverItems = useMemo(
    () =>
      (drivers.data ?? []).map((d) => ({
        label: friendlyDriverName(d) + (d.deprecated ? " (deprecated)" : ""),
        value: d.typeName,
      })),
    [drivers.data],
  );

  const trimmed = name.trim();
  const taken = trimmed.length > 0 && existing.some((v) => v.name === trimmed);
  const canSubmit = trimmed.length > 0 && !taken && !!typeName;

  const submit = () => {
    if (!canSubmit || !scopeBundle) return;
    const newVar: VariableDefinition = {
      id: crypto.randomUUID(),
      name: trimmed,
      typeName,
      isArray,
      value: value === "" ? null : value,
      storageDriverTypeName: storage || null,
    };
    scopeBundle.setVariables([...existing, newVar]);
    toast.success(`Variable “${trimmed}” created.`);
    onCreated?.(newVar);
    onClose();
  };

  return (
    <>
      <DialogHeader>
        <DialogTitle>New variable</DialogTitle>
        <DialogDescription>
          {scopeBundle?.scope.kind === "container"
            ? `Variable is scoped to ${scopeBundle.scope.label} — visible only to activities inside that container.`
            : "Variables live on the workflow definition and can be read or written from any activity."}
        </DialogDescription>
      </DialogHeader>
      <form
        className="flex flex-col gap-3"
        onSubmit={(e) => {
          e.preventDefault();
          submit();
        }}
      >
        <div className="grid gap-1.5">
          <Label htmlFor="cv-name">Name</Label>
          <Input
            id="cv-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            aria-invalid={taken || undefined}
            autoFocus
          />
          {taken ? (
            <p className="text-destructive text-xs">A variable with this name already exists.</p>
          ) : null}
        </div>

        <div className="grid gap-1.5">
          <Label htmlFor="cv-type">Type</Label>
          <Select
            items={typeItems}
            value={typeName}
            onValueChange={(v) => v && setTypeName(v)}
          >
            <SelectTrigger id="cv-type" size="sm" className="w-full">
              <SelectValue placeholder={types.isPending ? "Loading…" : "Choose a type"} />
            </SelectTrigger>
            <SelectContent>
              {groupedTypes.map(([category, items]) => (
                <SelectGroup key={category}>
                  <SelectLabel>{category}</SelectLabel>
                  {items.map((t) => (
                    <SelectItem key={t.typeName} value={t.typeName}>
                      {friendlyTypeName(t)}
                    </SelectItem>
                  ))}
                </SelectGroup>
              ))}
            </SelectContent>
          </Select>
        </div>

        <Label className="flex cursor-pointer items-center gap-2 text-xs font-normal">
          <Checkbox checked={isArray} onCheckedChange={(c) => setIsArray(c)} />
          Is array
        </Label>

        <div className="grid gap-1.5">
          <Label htmlFor="cv-value">Default value (optional)</Label>
          <Input id="cv-value" value={value} onChange={(e) => setValue(e.target.value)} />
        </div>

        <div className="grid gap-1.5">
          <Label htmlFor="cv-storage">Storage driver</Label>
          <Select
            items={driverItems}
            value={storage}
            onValueChange={(v) => v && setStorage(v)}
          >
            <SelectTrigger id="cv-storage" size="sm" className="w-full">
              <SelectValue placeholder={drivers.isPending ? "Loading…" : "Default"} />
            </SelectTrigger>
            <SelectContent>
              {(drivers.data ?? []).map((d) => (
                <SelectItem key={d.typeName} value={d.typeName}>
                  {friendlyDriverName(d)}
                  {d.deprecated ? (
                    <span className="text-muted-foreground ml-1 text-2xs">(deprecated)</span>
                  ) : null}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <DialogFooter>
          <DialogClose render={<Button variant="outline" type="button" />}>Cancel</DialogClose>
          <Button type="submit" disabled={!canSubmit}>
            Create variable
          </Button>
        </DialogFooter>
      </form>
    </>
  );
}

function friendlyTypeName(t: VariableTypeDescriptor): string {
  return friendlyTypeLabel(t.displayName, t.typeName);
}

/**
 * Storage drivers' server-side `displayName` usually already drops the
 * "StorageDriver" suffix, but if a driver registered itself with the
 * assembly-qualified name we need to clean it up like a type name and
 * then strip the suffix.
 */
function friendlyDriverName(d: StorageDriverDescriptor): string {
  if (d.displayName && !d.displayName.includes(",") && !d.displayName.includes(".")) {
    return d.displayName;
  }
  return shortenTypeName(d.displayName || d.typeName).replace(/StorageDriver$/, "");
}
